"""Central configuration constants for the migration."""

from __future__ import annotations

from pathlib import Path

WEBFLOW_API_TOKEN_ENV = "WEBFLOW_API_TOKEN"
WEBFLOW_SITE_ID_ENV = "WEBFLOW_SITE_ID"
WEBFLOW_COLLECTION_ID_ENV = "WEBFLOW_COLLECTION_ID"
TOD_GALLERIES_COLLECTION_ID_ENV = "TOD_GALLERIES_COLLECTION_ID"
GALLERY_PHOTOS_COLLECTION_ID_ENV = "GALLERY_PHOTOS_COLLECTION_ID"
TOD_GALLERY_PHOTOS_COLLECTION_ID_ENV = "TOD_GALLERY_PHOTOS_COLLECTION_ID"
TOD_PHOTO_SETS_COLLECTION_ID_ENV = "TOD_PHOTO_SETS_COLLECTION_ID"
DEFAULT_GALLERY_PHOTOS_CSV = Path("tod-gallery-photo-descriptions.csv")
LEGACY_GALLERY_PHOTOS_CSV = Path("tod_gallery_photos.csv")
DEFAULT_GALLERY_PHOTOS_SCHEMA = Path("gallery-photos-schema.json")
DEFAULT_GALLERY_PHOTOS_FIELD_MAP = Path("gallery-photos-field-map.json")

API_BASE = "https://api.webflow.com/v2"
RETRYABLE_STATUS_CODES = frozenset({429, 500, 502, 503, 504})
SUPPORTED_IMAGE_EXTENSIONS = frozenset(
    {".png", ".jpg", ".jpeg", ".gif", ".webp", ".avif"}
)

TARGET_IMAGE_WIDTH = 1600
TARGET_IMAGE_HEIGHT = 1200
ALLOW_IMAGE_UPSCALING = False
PROCESSED_IMAGES_DIRECTORY = Path("processed-gallery-images")

DEFAULT_MAX_IMAGE_BYTES = 4 * 1024 * 1024
DEFAULT_GALLERY_BATCH_SIZE = 10
DEFAULT_MAX_IMAGES_PER_GALLERY_FIELD = 25
DEFAULT_SPECIAL_FEATURES_FILENAME = "Special-Features-Picture.png"
DEFAULT_HERO_PATTERN = r"(?:^|[-_])G\d+(?:[-_]|$)"

WEBFLOW_BATCH_LIMIT = 100
DEFAULT_REQUEST_TIMEOUT = 60
DEFAULT_MAX_RETRIES = 5
